# Generated by Django 6.1.1 on 2026-09-15 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diywork',
            name='summary',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='简介'),
        ),
        migrations.AddField(
            model_name='diywork',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='视频文件'),
        ),
        migrations.AddField(
            model_name='diywork',
            name='work_type',
            field=models.CharField(choices=[('article', '图文'), ('video', '视频')], default='article', max_length=20, verbose_name='作品类型'),
        ),
        migrations.CreateModel(
            name='WorkAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='文件名')),
                ('file', models.FileField(upload_to='attachments/', verbose_name='文件')),
                ('size', models.BigIntegerField(default=0, verbose_name='大小(字节)')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='contentapp.diywork', verbose_name='作品')),
            ],
            options={
                'verbose_name': '作品附件',
                'verbose_name_plural': '作品附件',
                'ordering': ['-create_time'],
            },
        ),
    ]
